### ISSUE TITLE
Works in the Arduino IDE, not in PlatformIO

### ISSUE THREAD

**Issue by Klauzen** [micooke/SoftwareI2C#2]
Hello, thanks for sharing this library!
The example SoftwareI2C_Scan is working very well in the Arduino IDE. Now i tried to open the example in the PlatformIO IDE. Sadly, there are some warnings (but the compiler succeed). After uploading, I can't read any I2C devices. If I upload the same script via Arduino IDE, everything works perfect again..

These are the warning from the PlatformIO compiler:
`In file included from src\main.cpp:5:
src/SoftwareI2C.h: In constructor 'SoftwareI2C::SoftwareI2C(uint8_t, uint8_t)':
src/SoftwareI2C.h:85:13: warning: 'SoftwareI2C::_pinScl' will be initialized after [-Wreorder]
     uint8_t _pinScl;
             ^~~~~~~
src/SoftwareI2C.h:84:13: warning:   'uint8_t SoftwareI2C::_pinSda' [-Wreorder]
     uint8_t _pinSda;
             ^~~~~~~
src/SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
src/SoftwareI2C.h:84:13: warning: 'SoftwareI2C::_pinSda' will be initialized after [-Wreorder]
     uint8_t _pinSda;
             ^~~~~~~
src/SoftwareI2C.h:56:10: warning:   'bool SoftwareI2C::_transmissionBegun' [-Wreorder]
     bool _transmissionBegun;
          ^~~~~~~~~~~~~~~~~~
src/SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
src/SoftwareI2C.h:56:10: warning: 'SoftwareI2C::_transmissionBegun' will be initialized after [-Wreorder]
     bool _transmissionBegun;
          ^~~~~~~~~~~~~~~~~~
src/SoftwareI2C.h:54:13: warning:   'uint8_t SoftwareI2C::_i2c_address' [-Wreorder]
     uint8_t _i2c_address;
             ^~~~~~~~~~~~
src/SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
In file included from src\SoftwareI2C.cpp:25:
src\SoftwareI2C.h: In constructor 'SoftwareI2C::SoftwareI2C(uint8_t, uint8_t)':
src\SoftwareI2C.h:85:13: warning: 'SoftwareI2C::_pinScl' will be initialized after [-Wreorder]
     uint8_t _pinScl;
             ^~~~~~~
src\SoftwareI2C.h:84:13: warning:   'uint8_t SoftwareI2C::_pinSda' [-Wreorder]
     uint8_t _pinSda;
             ^~~~~~~
src\SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
src\SoftwareI2C.h:84:13: warning: 'SoftwareI2C::_pinSda' will be initialized after [-Wreorder]
     uint8_t _pinSda;
             ^~~~~~~
src\SoftwareI2C.h:56:10: warning:   'bool SoftwareI2C::_transmissionBegun' [-Wreorder]
     bool _transmissionBegun;
          ^~~~~~~~~~~~~~~~~~
src\SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
src\SoftwareI2C.h:56:10: warning: 'SoftwareI2C::_transmissionBegun' will be initialized after [-Wreorder]
     bool _transmissionBegun;
          ^~~~~~~~~~~~~~~~~~
src\SoftwareI2C.h:54:13: warning:   'uint8_t SoftwareI2C::_i2c_address' [-Wreorder]
     uint8_t _i2c_address;
             ^~~~~~~~~~~~
src\SoftwareI2C.h:86:5: warning:   when initialized here [-Wreorder]
     SoftwareI2C(uint8_t pinSda = 7, uint8_t pinScl = 8) : _pinScl(pinScl), _pinSda(pinSda), _transmissionBegun(false), _i2c_address(0x3C) { setClock(100000); }
     ^~~~~~~~~~~
In file included from src\main.cpp:7:
src/i2c_device_list.h: In function 'arduino::String i2c_device_list(uint8_t)':
src/i2c_device_list.h:292:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^`

Can you give me some hints to solve this problem?

Thanks a lot!

**Comment by micooke** [comment]
Those ```-Wreorder``` messages are annoying, but not the issue.
That last message - it looks like I forgot to add a default return to ```i2c_device_list()``` in ```i2c_device_list.h```. Which i should fix.

Having said all this, i never planned to support PlatformIO and I have never used it so that's the cause of the error. I'm probably missing something it needs. Otherwise, the dump you provided is all warnings so it should still compile

**Comment by Klauzen** [comment]
Hello, thanks for replying!
I added the return without solving the problem. 
Now, i'm trying to get help in the PlatformIO community ;-)
Regards!

**Comment by micooke** [comment]
Goodluck! Please let me know what you find/create a pull request and I will try to slowly ammend the other libraries I have to be compatible with PlatformIO

**Comment by Klauzen** [comment]
Thanks. What about this ToDo in the code:
`    // Note : tunedDelay should be used to throttle comms by appropriately delaying the SCL toggling
    //        However the I2C devices i work with are tolerant to non-standard rates, so this is not implemented
#ifdef __AVR__
    inline void tunedDelay(uint16_t delay_us) { _delay_loop_2(delay_us / _avr_bit_delay_scaling); }
#else
    inline void tunedDelay(uint16_t delay_us)
    {
      // TODO: Measure how long digitalWrite, pinMode etc take and compensate by this
      // maybe use ___attribute__( ( always_inline ) ) static __INLINE void __NOP(void) { __ASM volatile ("nop"); }
      // to create a _delay_loop_2() ?
      delayMicroseconds(delay_us);
    }
#endif`

Could this cause problems by using non-AVR boards? Thank you!

**Comment by micooke** [comment]
I actually wrote this for the nRF5 series of mcu's, then added the avr specific code later.
But I dont see a problem with that code.
Whats the exact error you get?

**Comment by Klauzen** [comment]
Hi. There were no errors. In the meanwhile i compiled the same code with Visual Studio Micro and Arduino Pro IDE (Beta) and it works. So I will not use PlatformIO anymore! Thanks for helping me!

**Comment by micooke** [comment]
Excellent! I hope it works well for you. Good luck Lukas 😁
